# Generated by Django 5.2.7 on 2025-10-07 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orphan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='orphans.orphan')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('enrolled_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphans.course')),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='orphans.orphan')),
            ],
            options={
                'unique_together': {('orphan', 'course')},
            },
        ),
    ]
